### ISSUE TITLE
Monday, May 11, Instructor Consultations

### ISSUE THREAD

**Issue by rickecon** [UC-MACSS/persp-research-econ_Spr20#6]
Dear MACS 30250 Perspectives on Computational Economics Research students,

I have posted a schedule of available times for your Monday, May 11 office consultations with me on the [`OfficeVisits/README.md`](https://github.com/UC-MACSS/persp-research-econ_Spr20/blob/master/OfficeVisits/README.md). These consultations will be held instead of class on Monday, May 11 as a way for me to help those of you who need a push on your projects. These visits are optional. The visits will be held via my Zoom meeting office hour ID ([https://uchicago.zoom.us/j/95309345411](https://uchicago.zoom.us/j/95309345411)). Any who sign up will have 15 minutes with me in which we can discuss and assess:

* Your progress on your paper
* Any issues you might be having
* Any suggestions from Dr. Evans

If you would like to schedule a time, please respond to this issue with the time you would prefer. I will update the schedule as your responses come in. If you need a time that is not on the schedule, I can be flexible.

@heathercchen @bazirou @hihowme @Leahjl @PAHADRIANUS @luyingjiang @wu-yt @ekarsten @yutianlai @ChivLiu @yongfeilu @lulululugagaga @Panyw97 @caibengbu @RuoyunTan @luxin-tian @linghui-wu @ZhouXing-19 @WMhYang @Kent0417 @timqzhang @Yiqing-Zh @Anqi-Zhou

**Comment by ekarsten** [comment]
I would like to schedule a meeting, and I am open to any time, so feel free to move me around as other people have particular scheduling needs.

**Comment by rickecon** [comment]
@ekarsten . Just choose a time that you prefer, and I can move you around as needed.

**Comment by ekarsten** [comment]
I'll go with 2pm

**Comment by wu-yt** [comment]
Can I schedule a meeting at 3:30? Thank you!

**Comment by yutianlai** [comment]
I would like to choose 2:30pm. Thanks!

**Comment by Leahjl** [comment]
I would like to choose 3:00 pm.Thanks!


| |
Jielu He
|
|
邮箱：hejielu1996@yeah.net
|

Signature is customized by Netease Mail Master

On 05/06/2020 11:50, Richard Evans wrote:

Dear MACS 30250 Perspectives on Computational Economics Research students,

I have posted a schedule of available times for your Monday, May 11 office consultations with me on the OfficeVisits/README.md. These consultations will be held instead of class on Monday, May 11 as a way for me to help those of you who need a push on your projects. These visits are optional. The visits will be held via my Zoom meeting office hour ID (https://uchicago.zoom.us/j/95309345411). Any who sign up will have 15 minutes with me in which we can discuss and assess:

Your progress on your paper
Any issues you might be having
Any suggestions from Dr. Evans

If you would like to schedule a time, please respond to this issue with the time you would prefer. I will update the schedule as your responses come in. If you need a time that is not on the schedule, I can be flexible.

@heathercchen@bazirou@hihowme@Leahjl@PAHADRIANUS@luyingjiang@wu-yt@ekarsten@yutianlai@ChivLiu@yongfeilu@lulululugagaga@Panyw97@caibengbu@RuoyunTan@luxin-tian@linghui-wu@ZhouXing-19@WMhYang@Kent0417@timqzhang@Yiqing-Zh@Anqi-Zhou

**Comment by ye-sun-econ** [comment]
Dear Dr. Evans, can I schedule a meeting at 1:30 pm please?
